DapperAdvanced/Models/Bike.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DapperAdvanced.Models
{
    public class Bike
    {
        public int Id { get; set; }
        [Required]
        [MaxLength(50)]
        public string Name { get; set; }
        [Required]
        [MaxLength(50)]
        public string Type { get; set; }
        [Required]
        [Display(Name = "Price of Bike")]
        public int Price { get; set; }
        [Required]
        [MaxLength(50)]
        [Display(Name = "Company Name")]
        public string Company { get; set; }
        
        }
    }

DapperAdvanced/Controllers/BikeController.cs
using DapperAdvanced.Models;
using Microsoft.Office.Interop.Excel;
using OfficeOpenXml;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;
using Glimpse.AspNet.Tab;
using NPOI.HSSF.UserModel;

namespace DapperAdvanced.Controllers
{
    public class BikeController : Controller
    {
        // GET: Bike
        private BikesRepository repository;

        public BikeController()
        {
            repository = new BikesRepository();
        }
        public ActionResult Index(RequestModel request)
        {
            if (request.OrderBy == null)
            {
                request = new RequestModel
                {
                    Search = request.Search,
                    OrderBy = "name",
                    IsDescending = false,


                };
            }
          
            ViewBag.Request = request;
            return View(repository.GetAll(request));
        }




        public ActionResult Details(int id)
        {
            return View(repository.Get(id));
        }



        // GET: Bike/Details/5


        // GET: Bike/Create
        public ActionResult Create()
        {
            var Biketypes = new List<string>() {  "Normal",  "Stunt", "Sport" };
            ViewBag.Biketypes = Biketypes;
            return View();
        }

        // POST: Bike/Create
        [HttpPost]
        public ActionResult Create(Bike bike, bool editAfterSaving = false)
        {
            if (ModelState.IsValid)
            {
                var lastInsertedId = repository.Create(bike);
                if (lastInsertedId > 0)
                {
                    TempData["Message"] = "Record added successfully";
                }
                else
                {
                    TempData["Error"] = "Failed to add record";
                }
                if (editAfterSaving)
                {
                    return RedirectToAction("Edit", new { Id = lastInsertedId });
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
            
            return View();
        }

        // GET: Bike/Edit/5
        public ActionResult Edit(int id)
        {


            var Biketypes = new List<string>() { "Normal", "Stunt", "Sport" };
            ViewBag.Biketypes = Biketypes;

            return View(repository.Get(id));
        }
        

        // POST: Bike/Edit/5
        [HttpPost]
        public ActionResult Edit(Bike bike)
        {
            if (ModelState.IsValid)
            {
                var recordAffected = repository.Update(bike);
                if (recordAffected > 0)
                {
                    TempData["Message"] = "Record updated successfully";
                }
                else
                {
                    TempData["Error"] = "Failed to update record";
                }
                return RedirectToAction("Index");
            }
            return View();
        }

        // GET: Bike/Delete/5
        public ActionResult Delete(int id)
        {
            return View(repository.Get(id));
        }

        // POST: Bike/Delete/5
        [HttpPost]
        public ActionResult Delete(Bike bike)
        {
            var recordAffected = repository.Delete(bike.Id);
            if (recordAffected > 0)
            {
                TempData["Message"] = "Record deleted successfully";
            }
            else
            {
                TempData["Error"] = "Failed to delete record";
            }
            return RedirectToAction("Index");
        }



        //public ActionResult ExportToExcel()
        //{

        //    BikesRepository repository = new BikesRepository();
        //    RequestModel request = new RequestModel();
        //    var model = repository.GetAll(request);

        //    HSSFWorkbook templateWorkbook = new HSSFWorkbook();
        //    HSSFSheet sheet = (HSSFSheet)templateWorkbook.CreateSheet("Index");
        //    List<Bike> _Bike = model.ToList();
        //    HSSFRow dataRow = (HSSFRow)sheet.CreateRow(0);
        //    HSSFCellStyle style = (HSSFCellStyle)templateWorkbook.CreateCellStyle();

        //    HSSFFont font = (HSSFFont)templateWorkbook.CreateFont();
        //    font.Color = NPOI.HSSF.Util.HSSFColor.White.Index;
        //    HSSFCell cell;
        //    style.SetFont(font);

        //    cell = (HSSFCell)dataRow.CreateCell(0);
        //    cell.CellStyle = style;
        //    cell.SetCellValue("No.");

        //    cell = (HSSFCell)dataRow.CreateCell(1);
        //    cell.CellStyle = style;
        //    cell.SetCellValue("Name");
        //    cell = (HSSFCell)dataRow.CreateCell(2);
        //    cell.CellStyle = style;
        //    cell.SetCellValue("Type");
        //    cell = (HSSFCell)dataRow.CreateCell(3);
        //    cell.CellStyle = style;
        //    cell.SetCellValue("Price");
        //    cell = (HSSFCell)dataRow.CreateCell(4);
        //    cell.CellStyle = style;
        //    cell.SetCellValue("Company");

        //    for (int i = 0; i < _Bike.Count; i++)
        //    {
        //        dataRow = (HSSFRow)sheet.CreateRow(i + 1);
        //        dataRow.CreateCell(0).SetCellValue(i + 1);
        //        dataRow.CreateCell(1).SetCellValue(_Bike[i].Name);
        //        dataRow.CreateCell(2).SetCellValue(_Bike[i].Type);
        //        dataRow.CreateCell(3).SetCellValue(_Bike[i].Price);
        //        dataRow.CreateCell(3).SetCellValue(_Bike[i].Company);
        //    }
        //    MemoryStream ms = new MemoryStream();
        //    templateWorkbook.Write(ms);
        //    return File(ms.ToArray(), "application/vnd.ms-excel", "Bikes.xls");


        //}
    }
}

DapperAdvanced/Views/Bike/Create.cshtml
@model DapperAdvanced.Models.Bike

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Bike</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(Model => Model.Type, new SelectList(ViewBag.listitems),"Select Bike Type",htmlAttributes: new { @class = "form-control" })

            @*@Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })*@
            @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })

        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Company, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Company, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Company, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label for="editAfterSaving"
               class="control-label col-md-2">Edit after Saving</label>
        <div class="col-md-10">
            <input id="editAfterSaving" name="editAfterSaving" type="checkbox" value="true" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-outline-primary" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
   
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DapperAdvanced/Views/Bike/Delete.cshtml
@model DapperAdvanced.Models.Bike

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Bike</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Company)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Company)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DapperAdvanced/Views/Bike/Details.cshtml
@model DapperAdvanced.Models.Bike

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Bike</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Company)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Company)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DapperAdvanced/Views/Bike/Edit.cshtml
@model DapperAdvanced.Models.Bike

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Bike</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(Model => Model.Type, new SelectList(ViewBag.listitems), "Select Bike Type", htmlAttributes: new { @class = "form-control" })

                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Company, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Company, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Company, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-outline-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DapperAdvanced/Views/Bike/Index.cshtml
@model DapperAdvanced.Models.PagedList<DapperAdvanced.Models.Bike>
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />


@{
    ViewBag.Title = "Index";
}

<h2>Bikes</h2>

<div class="row pb-3">
    <div class="col-md-6">
        <form method="get" action="@Url.Action("Index")">
            <input name="Search" type="search" placeholder="Search" value="@ViewBag.Request.Search" />
            <button class="btn btn-primary">Search</button>
        </form>
    </div>


    <div class="col-md-6 text-end">
        @Html.ActionLink("Create New", "Create", null,
        new { @class = "btn btn-primary" })
        <button class="btn btn-primary" type="submit" value="print" onclick="window.print()">Print</button>
        <a href="@Url.Action("Index","Bike",
                new DapperAdvanced.Models.RequestModel
                {
                    Search=ViewBag.request.Search,
                OrderBy=ViewBag.request.OrderBy,
                IsDescending= ViewBag.request.IsDescending,
                PageSize= 5
                })" class="=btn btn-primary">Export to Excel</a>
        @*@Html.ActionLink("ExportToExcel", "ExportToExcel", null,
        new { @class = "btn btn-primary" })*@
        <button class="btn btn-primary" onclick="openFullscreen()" id="toggle-fullscreen">Open Fullscreen</button>

        @Html.ActionLink("Refresh", "Index", null,
        new { @class = "btn btn-primary" })

    </div>

</div>
<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Name", "Index"
                 , new DapperAdvanced.Models.RequestModel
                 {
                     Search = ViewBag.Request.Search,
                     OrderBy = "name",
                     IsDescending = (ViewBag.Request.OrderBy == "name"
                                     &&
                                     ViewBag.Request.IsDescending == false) ? true : false
                 }, null)
        </th>
        <th>
            @Html.ActionLink("Type", "Index"
                 , new DapperAdvanced.Models.RequestModel
                 {
                     Search = ViewBag.Request.Search,
                     OrderBy = "type",
                     IsDescending = (ViewBag.Request.OrderBy == "type"
                                     &&
                                     ViewBag.Request.IsDescending == false) ? true : false
                 }, null)
        </th>
        <th>
            @Html.ActionLink("Price", "Index"
                  , new DapperAdvanced.Models.RequestModel
                  {
                      Search = ViewBag.Request.Search,
                      OrderBy = "Price",
                      IsDescending = (ViewBag.Request.OrderBy == "price"
                                      &&
                                      ViewBag.Request.IsDescending == false) ? true : false
                  }, null)
        </th>
        <th>
            @Html.ActionLink("Company", "Index"
                 , new DapperAdvanced.Models.RequestModel
                 {
                     Search = ViewBag.Request.Search,
                     OrderBy = "Company",
                     IsDescending = (ViewBag.Request.OrderBy == "Company"
                                     &&
                                     ViewBag.Request.IsDescending == false) ? true : false
                 }, null)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.Items)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Company)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

<div class="pagination" style="margin-left: 400px">

    <a href = "@Url.Action("Index", "Bike", new DapperAdvanced.Models.RequestModel
{
    Search = ViewBag.request.Search,
    OrderBy = ViewBag.Request.OrderBy,
    IsDescending = ViewBag.request.IsDescending,
    PageNumber = 1
})" class="btn btn-primary"></a>
</div>
<div class=" col text-end ">
    Page Size:
    <a href="@Url.Action("Index","Bike",
            new DapperAdvanced.Models.RequestModel
            {
                Search=ViewBag.request.Search,
                OrderBy=ViewBag.request.OrderBy,

                IsDescending= ViewBag.request.IsDescending,
                PageSize= 5,
            })" class="btn btn-primary">5</a>
    <a href="@Url.Action("Index","Bike",
            new DapperAdvanced.Models.RequestModel
            {
                Search=ViewBag.request.Search,
                OrderBy=ViewBag.request.OrderBy,

                IsDescending= ViewBag.request.IsDescending,
                PageSize= 10,
            })" class="btn btn-primary">10</a>

</div>






<script>

    var elem = document.documentElement;
    function openFullscreen() {
        if (elem.requestFullscreen) {
            elem.requestFullscreen();
        } else if (elem.webkitRequestFullscreen) {
            elem.webkitRequestFullscreen();
        } else if (elem.msRequestFullscreen) {
            elem.msRequestFullscreen();
        }
    }
</script>